name: 'Escalate AWS Privileges and Print Identity'

on:
  workflow_dispatch: # Allows manual execution

permissions:
  id-token: write  # Required to request an OIDC token
  contents: read   # Required for repository content access

jobs:
  escalate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::683350395763:role/sts-lab-2-target  # Replace with the actual role ARN
        role-session-name: EscalationSession

    - name: Print AWS STS Caller Identity
      run: |
        # Print the identity of the assumed role
        aws iam list-roles
      shell: bash
